### ISSUE TITLE
Link to a paper or some literature?

### ISSUE THREAD

**Issue by dispalt** [DmitryOlshansky/jsm4s#1]
Are there link to papers where I could learn more about this method, it looks interesting!

**Comment by DmitryOlshansky** [comment]
I'm about to do publish an intro blog post, any ideas where should I try to share it?

**Comment by DmitryOlshansky** [comment]
Speaking of publications, yes there would be a link or two. Problem is most of the material is in Russian :(

**Comment by dispalt** [comment]
Definitely, maybe hacker news and /r/scala, /r/programming on reddit.

**Comment by DmitryOlshansky** [comment]
Here it goes, also at the top of README now.
https://olshansky.me/jsm/ml/scala/2017/08/05/jsm-as-machine-learning.html

I failed to make even the tiniest splash on HN, maybe you'll have better luck in spreading the word.

**Comment by dispalt** [comment]
I posted on /r/scala and upvoted on HN.  Ill post in a couple weeks if it doesn't get much.

**Comment by DmitryOlshansky** [comment]
We got 1 star on GH, hooray!
Seriously thoughI should have tailored blog a bit more towards Scala users and/or post at fifferent time. Anyhow I guess this issue is closed.

Will post each subsequent release on Scala users. They would be mostly about playing with different datasets and tuning jsm4s to better handle them.

**Comment by dispalt** [comment]
Someone made this comment on reddit, btw. https://www.reddit.com/r/scala/comments/6s8mze/jsm_as_machine_learning/

What does JSM stand for?

**Comment by DmitryOlshansky** [comment]
I've answered there. I'll make a few adjustments to the post as well, including this historical bit.

**Comment by dispalt** [comment]
You could also star it yourself and get an additional star.

**Comment by DmitryOlshansky** [comment]
I was only joking. Stars aren't important, getting users and contributors is.

**Comment by dispalt** [comment]
haha yeah same =)
